/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.philimones.hds.explorer.installer;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIDefaults;

/**
 *
 * @author paul
 */
public class PanelWelcome extends javax.swing.JPanel implements IPage {

    /**
     * Creates new form PanelWelcome
     */
    public PanelWelcome() {
        initComponents();
        
        Color bgColor = new Color(214, 217, 223);
        
        UIDefaults defaults = new UIDefaults();
        defaults.put("EditorPane[Enabled].backgroundPainter", bgColor);
        label3Info.putClientProperty("Nimbus.Overrides", defaults);
        label3Info.putClientProperty("Nimbus.Overrides.InheritDefaults", true);
        label3Info.setBackground(bgColor);

    }

    private void openUrl(URI uri) {
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(uri);
            } catch (IOException ex) {
                Logger.getLogger(PanelWelcome.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label1setup = new javax.swing.JLabel();
        label2welcome = new javax.swing.JLabel();
        label3Info = new javax.swing.JEditorPane();
        label4mainsite = new javax.swing.JLabel();
        label5servesite = new javax.swing.JLabel();
        label6mobilesite = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(701, 473));
        setPreferredSize(new java.awt.Dimension(701, 473));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nio splash.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(312, 469));
        jLabel1.setMinimumSize(new java.awt.Dimension(312, 469));
        jLabel1.setPreferredSize(new java.awt.Dimension(312, 469));

        label1setup.setFont(new java.awt.Font("Gordita", 1, 14)); // NOI18N
        label1setup.setText("Setup HDS-Explorer Server");

        label2welcome.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        label2welcome.setText("Welcome to the HDS-Explorer Server Setup wizard");

        label3Info.setEditable(false);
        label3Info.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        label3Info.setContentType("text/html"); // NOI18N
        label3Info.setText("<html>   <head></head>   <body>    HDS-Explorer Server application provides the data repository for  a Health and Demographics Surveillance system and data management tool   for data collection for program or research implementation.    <br><br> This setup wizard will help you customize the HDS-Explorer parameters to meet your HDSS Site,  after it finishes a Java WAR archive will be generated with the defined parameters.  <br> <br> <b>More information about HDS-Explorer</b><br><br>   </body> </html> ");
        label3Info.setFocusable(false);

        label4mainsite.setForeground(java.awt.Color.blue);
        label4mainsite.setText("<html><u>https://www.hds-explorer.org </u></html>");
        label4mainsite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label4mainsite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4mainsiteMouseClicked(evt);
            }
        });

        label5servesite.setForeground(java.awt.Color.blue);
        label5servesite.setText("<html><u>HDS-Explorer Server source-code</u></html>");
        label5servesite.setToolTipText("");
        label5servesite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label5servesite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label5servesiteMouseClicked(evt);
            }
        });

        label6mobilesite.setForeground(java.awt.Color.blue);
        label6mobilesite.setText("<html><u>HDS-Explorer Mobile source-code</u></html>");
        label6mobilesite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1setup)
                    .addComponent(label2welcome)
                    .addComponent(label4mainsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5servesite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6mobilesite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3Info, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label1setup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label2welcome)
                .addGap(40, 40, 40)
                .addComponent(label3Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label4mainsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(label5servesite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label6mobilesite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void label4mainsiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4mainsiteMouseClicked
        if (evt.getButton()==MouseEvent.BUTTON1) {
            String url = "https://www.hds-explorer.org";
            try {
                openUrl(new URI(url));
            } catch (URISyntaxException ex) {
                Logger.getLogger(PanelWelcome.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_label4mainsiteMouseClicked

    private void label5servesiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5servesiteMouseClicked
        if (evt.getButton()==MouseEvent.BUTTON1) {
            String url = "https://github.com/philimones-group/hds-explorer-server";
            try {
                openUrl(new URI(url));
            } catch (URISyntaxException ex) {
                Logger.getLogger(PanelWelcome.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_label5servesiteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label1setup;
    private javax.swing.JLabel label2welcome;
    private javax.swing.JEditorPane label3Info;
    private javax.swing.JLabel label4mainsite;
    private javax.swing.JLabel label5servesite;
    private javax.swing.JLabel label6mobilesite;
    // End of variables declaration//GEN-END:variables

    @Override
    public ValidationResult validatePage() {
        return new ValidationResult(ValidationType.SUCCESS, null, null);
    }

    @Override
    public Map<String, String> exportValues() {
        return null;
    }
}
