/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.philimones.hds.explorer.installer;

import java.awt.Desktop;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author paul
 */
public class PanelGoodbye extends javax.swing.JPanel implements IPage {

    /**
     * Creates new form PanelWelcome
     */
    public PanelGoodbye() {
        initComponents();
    }

    private void openUrl(URI uri) {
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(uri);
            } catch (IOException ex) {
                Logger.getLogger(PanelGoodbye.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label1setup = new javax.swing.JLabel();
        label2welcome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label4mainsite = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label6mobilesite = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label5servesite = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(701, 473));
        setPreferredSize(new java.awt.Dimension(701, 473));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nio splash.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(312, 469));
        jLabel1.setMinimumSize(new java.awt.Dimension(312, 469));
        jLabel1.setPreferredSize(new java.awt.Dimension(312, 469));

        label1setup.setFont(new java.awt.Font("Gordita", 1, 14)); // NOI18N
        label1setup.setText("Finalizing HDS-Explorer Setup wizard");

        label2welcome.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        label2welcome.setText("The setup configuration is finished!");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 11)); // NOI18N
        jLabel2.setText("The configuration generated 4 files that can be found in the output directory");

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, -150, 0));

        label4mainsite.setForeground(java.awt.Color.blue);
        label4mainsite.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label4mainsite.setText("<html><u>hds-explorer-server.war</u></html>");
        label4mainsite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(label4mainsite);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("<html>A java WAR file to be deployed in containers like Tomcat</html>");
        jPanel1.add(jLabel3);

        label6mobilesite.setForeground(java.awt.Color.blue);
        label6mobilesite.setText("<html><u>create-user-mysql.sql</u></html>");
        label6mobilesite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(label6mobilesite);

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        jLabel4.setText("An SQL file with database and user creation statements");
        jPanel1.add(jLabel4);

        label5servesite.setForeground(java.awt.Color.blue);
        label5servesite.setText("<html><u>app-config.yml</u></html>");
        label5servesite.setToolTipText("");
        label5servesite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(label5servesite);

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        jLabel5.setText("The app config. file that can be reused in other setups");
        jPanel1.add(jLabel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1setup)
                    .addComponent(label2welcome)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(label1setup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label2welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label1setup;
    private javax.swing.JLabel label2welcome;
    private javax.swing.JLabel label4mainsite;
    private javax.swing.JLabel label5servesite;
    private javax.swing.JLabel label6mobilesite;
    // End of variables declaration//GEN-END:variables

    @Override
    public ValidationResult validatePage() {
        return new ValidationResult(ValidationType.SUCCESS, null, null);
    }

    @Override
    public Map<String, String> exportValues() {
        return null;
    }
}
